export const WORD_POOLS = {
  easy: [
    // 2–3 letter everyday words
    "cat","dog","run","fun","sun","hat","big","red","hot","bed","cup","pen","map","sit",
    "hit","let","got","him","has","her","she","the","and","for","are","but","not","you",
    "all","had","was","one","our","out","day","get","how","man","new","now","old","see",
    "two","way","boy","put","say","too","use","dad","mom","yes","ago","air","car","eat",
    "end","far","job","may","off","own","ran","six","top","try","who","why","add","age",
    "bad","box","buy","cut","dry","ear","egg","eye","few","fly","gap","gas","ice","joy",
    "key","kid","leg","lip","lot","low","mad","mix","mud","net","nut","odd","oil","pay",
    "pit","pop","pot","raw","rub","rug","sad","sea","set","sky","tap","tax","tea","tie",
    "tip","toe","toy","van","war","wet","win","zip","zoo","arm","ask","bag","ban","bar",
    "bee","bet","bit","bug","bus","bye","cab","cap","cop","cow","cry","den","dot","dug",
    "dye","era","fan","fee","fig","fit","fix","fog","fry","fur","gel","gem","gum","gut",
    "oak","sob","ink","nod","eve","foe","lap","sap","map","nap","rap","wax","hex","vex",
    // 4 letter words
    "able","also","area","army","away","baby","back","ball","band","bank","base","bath",
    "bear","beat","been","bell","belt","best","bird","bite","blow","blue","boat","body",
    "bold","bone","book","boom","born","both","burn","call","calm","camp","card","care",
    "case","cash","cast","city","clap","clay","club","coal","coat","code","coin","cold",
    "come","cook","cool","corn","cost","dark","data","date","dead","deal","dear","deep",
    "desk","dirt","dish","door","dose","draw","drop","drug","drum","duck","dull","dump",
    "dust","duty","each","earn","ease","edge","else","even","ever","evil","exam","face",
    "fact","fail","fair","fall","fame","farm","fast","fate","feel","file","fill","film",
    "find","fine","fire","firm","fish","fist","flag","flat","flow","foam","fold","folk",
    "font","food","fool","foot","ford","fork","form","fort","foul","four","free","from",
    "fuel","full","fund","fuse","gain","game","gate","gave","gaze","gear","gift","girl",
    "give","glad","glow","goal","gold","good","grab","gray","grew","grid","grip","grow",
    "gulf","guru","gust","hack","hail","half","hall","halt","hand","hang","hard","harm",
    "harp","hate","have","hawk","head","heal","heap","heat","heel","held","help","herb",
    "here","hero","hide","high","hill","hire","hold","hole","home","hook","hope","horn",
    "host","hour","hunt","hurt","idea","idle","inch","into","iron","item","join","jump",
    "just","keen","keep","kept","kick","kill","kind","king","knit","know","lace","lack",
    "lake","lamp","land","lane","last","late","lead","leaf","lean","leap","left","lend",
    "lens","less","life","lift","like","line","link","list","live","load","loan","lock",
    "loft","lone","long","look","loop","lord","lore","lose","loss","lost","love","luck",
    "main","make","male","mall","malt","many","mark","mask","mass","mast","math","maze",
    "mean","meet","melt","memo","menu","mere","mesh","mile","milk","mill","mind","mine",
    "mint","miss","mode","mole","mood","moon","more","most","move","much","muse","must",
    "nail","name","navy","near","neck","need","nest","next","nice","node","none","noon",
    "norm","nose","note","noun","null","oath","once","only","open","oral","oven","over",
    "page","pain","pair","palm","park","part","pass","past","path","peak","peel","peer",
    "pick","pink","pipe","plan","play","plot","plow","plug","plus","poem","poet","pole",
    "poll","pond","pool","poor","port","pose","post","pour","prey","prod","pull","pump",
    "pure","push","quit","quiz","race","rack","raid","rail","rain","ramp","rank","rare",
    "rate","read","real","reel","reef","rely","rent","rest","rice","rich","ride","ring",
    "rise","risk","road","roam","roar","rock","role","roll","roof","room","rope","rose",
    "ruin","rule","rush","rust","safe","sage","sail","sale","salt","same","sand","save",
    "scan","scar","seal","seam","seed","seek","self","sell","send","sent","shed","ship",
    "shop","shot","show","shut","sick","side","sigh","sign","silk","sing","sink","site",
    "size","skin","skip","slam","slip","slow","slug","snap","snow","soda","soil","sold",
    "sole","some","song","soon","sort","soul","soup","span","spin","spit","spot","spur",
    "star","stay","stem","step","stir","stop","stub","such","suit","sure","swim","tail",
    "tale","tall","tank","tape","task","team","tear","tell","temp","tent","test","text",
    "than","that","them","then","they","thin","this","thus","tide","till","time","tiny",
    "tire","told","toll","tomb","tone","tool","torn","toss","tour","town","trap","tree",
    "trim","trip","true","tube","tune","turn","twin","type","ugly","upon","used","user",
    "vast","very","vest","view","vine","void","volt","vote","wade","wage","wake","walk",
    "wall","want","warm","warn","warp","wash","wave","weak","wear","weed","week","well",
    "went","were","what","when","whom","wide","wife","wild","will","wind","wine","wing",
    "wire","wise","wish","with","wolf","wood","word","work","worm","worn","wrap","wren",
    "yard","year","yell","your","zero","zone",
  ],
  medium: [
    "about","above","across","action","actual","acute","adapt","added","admit","adopt",
    "adult","after","again","agent","agree","ahead","alarm","album","alert","alike",
    "align","alive","alley","allow","alone","along","altar","alter","always","among",
    "angel","anger","angle","angry","anime","annex","apart","apple","apply","arena",
    "argue","arise","array","arrow","aside","avoid","awake","aware","badly","baker",
    "basic","basis","batch","beach","begin","being","below","bench","blend","bless",
    "blind","block","blood","bloom","board","bonus","boost","bound","brain","brand",
    "brave","bread","break","breed","brick","brief","bring","broad","broke","brook",
    "brown","brush","build","built","burst","buyer","cabin","cable","cache","candy",
    "carry","catch","cause","chair","chaos","charm","chart","chase","cheap","check",
    "chess","chest","chief","child","chose","civic","civil","claim","class","clean",
    "clear","clerk","click","cliff","climb","cling","clock","clone","close","cloth",
    "cloud","coach","coast","color","comma","comet","comic","coral","could","count",
    "court","cover","crack","craft","crane","crash","crazy","cream","creek","crime",
    "cross","crowd","crown","cruel","crush","curve","cycle","dance","death","debug",
    "decay","delay","dense","depot","depot","depth","derby","devil","digit","dirty",
    "disco","dodge","doing","doubt","draft","drama","drawn","dream","dress","drift",
    "drill","drink","drive","drone","drove","drunk","dunes","dwarf","eager","early",
    "earth","eight","elite","email","empty","enjoy","enter","epoch","equal","equip",
    "error","essay","event","exact","excel","exist","extra","fable","faint","faith",
    "false","fancy","fatal","fault","feast","fence","fever","fewer","field","fifth",
    "fifty","fight","final","first","fixed","flag","flame","flash","flask","flock",
    "flood","floor","flour","fluid","focal","focus","force","forge","found","frame",
    "frank","fraud","fresh","front","frost","fruit","funny","fuzzy","gauge","genus",
    "ghost","given","gland","glass","globe","gloom","glory","glove","going","grace",
    "grade","grain","grand","grant","graph","grasp","grass","grave","great","green",
    "grief","grind","groan","group","grove","guard","guess","guest","guide","guild",
    "guile","guilt","guise","gusto","happy","harsh","haven","heart","heavy","hence",
    "hinge","hints","honor","horse","hotel","house","human","humor","ideal","image",
    "imply","index","indie","infer","inner","input","issue","ivory","jewel","judge",
    "juice","juicy","jumpy","kanji","karma","knife","knock","known","label","large",
    "laser","later","laugh","layer","learn","lease","least","leave","legal","lemon",
    "level","light","limit","liner","local","logic","login","loose","lover","lower",
    "lucky","lunar","lying","magic","major","match","mayor","media","merge","merit",
    "metal","minor","minus","modal","model","month","moral","motor","mount","mouse",
    "mouth","music","naive","naval","nerve","never","night","ninja","noise","north",
    "noted","novel","nurse","nymph","occur","offer","often","ozone","ocean","olive",
    "omega","onion","onset","opera","order","organ","other","ought","outer","owner",
    "ozone","panda","panel","panic","paper","party","paste","patch","pause","peace",
    "pearl","pedal","penny","perch","phase","phone","photo","piano","piece","pilot",
    "pixel","pizza","place","plain","plane","plant","plate","plaza","plumb","plume",
    "plunk","point","polar","power","press","price","pride","prime","print","prior",
    "probe","proof","prose","proud","prove","proxy","pulse","purse","queue","queen",
    "query","quest","quick","quiet","quite","quota","quote","radar","radio","raise",
    "rally","range","rapid","ratio","reach","realm","rebel","regex","relay","reply",
    "reset","rider","ridge","right","rigid","risky","river","robin","robot","rocky",
    "roman","rouge","rough","round","route","royal","ruler","rural","sadly","saint",
    "sauce","scale","scene","score","scout","scary","sense","serve","seven","shade",
    "shall","shame","shape","share","shark","sharp","shift","shine","shirt","shock",
    "shore","short","sight","sigma","skate","skill","slate","slave","sleep","slice",
    "slide","slope","smart","smile","smoke","snake","solar","solid","solve","sonic",
    "sorry","south","space","spare","spark","speed","spend","spill","spine","spirit",
    "spite","split","spoke","spoon","squad","staff","stage","stake","stale","stamp",
    "stand","start","state","stats","steam","steel","steep","steer","stern","still",
    "stock","stone","stood","store","storm","story","stove","strip","stuck","study",
    "style","sugar","suite","super","surge","swamp","swear","sweep","sweet","swift",
    "swing","sword","taboo","their","theme","there","these","thick","thing","think",
    "those","three","threw","throw","thumb","tiger","timer","title","today","token",
    "topic","total","touch","tough","towel","tower","trace","track","trade","trail",
    "train","trait","trash","trial","tribe","trick","tried","trust","truth","tumor",
    "tuner","twist","tying","typed","ultra","under","union","unity","until","using",
    "usher","usual","utter","valid","value","valve","vapor","vault","video","viral",
    "virus","visit","vista","vital","vivid","vocal","voter","wagon","waste","watch",
    "water","weary","weird","whale","wheat","where","which","while","white","whole",
    "whose","wider","witch","woman","woods","world","worry","worse","worst","worth",
    "would","wound","write","wrong","yacht","yield","young","yours","youth",
  ],
  hard: [
    // 8–16 letter complex / rare words
    "aberration","abhorrence","abnormality","abominable","abruptness","absolution",
    "abstraction","acrimonious","acquiescent","adamantine","adversarial","affectation",
    "aggrandize","allegiance","ambiguity","ambivalence","ameliorate","anachronism",
    "anomalous","antithesis","apprehensive","apocryphal","arbitrary","archaic",
    "articulate","ascertain","assiduous","atrocious","audacious","avarice",
    "bafflement","belligerent","benevolent","blandishment","blasphemous","boisterous",
    "bureaucratic","cacophony","callousness","capricious","catastrophic","causticness",
    "circumvent","clandestine","coercive","cognizant","condescension","convoluted",
    "contemptuous","credential","cumbersome","cynicism","daunting","debilitating",
    "deceitful","deleterious","deprecate","derogatory","despondent","destructive",
    "devious","dilapidated","discordant","discrepancy","dissonance","dubious",
    "ebullient","egregious","elaborate","eloquence","ephemeral","equivocal",
    "exacerbate","exorbitant","exhaustive","exuberant","facetious","fallacious",
    "fastidious","flabbergasted","fortuitous","frivolous","garrulous","grandiose",
    "gratuitous","gregarious","hallucinate","hypocritical","idiosyncratic","impetuous",
    "inadvertent","incorrigible","indefatigable","indigenous","inexorable","innocuous",
    "insidious","intransigent","irrelevance","juxtaposition","labyrinthine","loquacious",
    "magnanimous","malevolent","mercurial","meticulous","mischievous","misanthrope",
    "nefarious","negligence","nomenclature","nonchalance","obfuscate","obstinate",
    "omnipotent","ostentatious","paradoxical","perfidious","perspicacious","phlegmatic",
    "pragmatic","precarious","preposterous","pretentious","proclivity","procrastinate",
    "profligate","propitious","pugnacious","querulous","quintessential","recalcitrant",
    "reciprocate","rectitude","relinquish","reprehensible","resilience","reticent",
    "sagacious","sanguine","scrupulous","serendipity","superfluous","surreptitious",
    "tenacious","trepidation","ubiquitous","unequivocal","vacuous","veracious",
    "vicarious","vehement","whimsical","xenophobia","zealotry","zealous","melancholy",
    "flummoxed","discombobulate","obstreperously","prestidigitation","scintillating",
    "serendipitous","sesquipedalian","sycophantic","transmogrify","troglodyte",
    "vicissitude","abdication","abnegation","abscond","acrimony","acquisitive",
    "admonishment","affronted","amalgamate","amelioration","anathema","anthropomorphic",
  ],
};

export const NUMBER_TOKENS = [
  "0","1","2","3","4","5","6","7","8","9",
  "10","11","12","13","14","15","16","17","18","19","20",
  "24","30","42","50","64","75","99","100","128","256","404","500","1000",
];

export const SYMBOL_TOKENS = [
  "!","@","#","$","%","^","&","*","?","+","-","=",";",":",",",
  "/","~",".","!","@","#",
];

export const DIFF_META = {
  easy:   { label: "easy",   accent: "#22d3a5" },
  medium: { label: "medium", accent: "#f7b731" },
  hard:   { label: "hard",   accent: "#fc5c65" },
};

export const TIME_PRESETS = [15, 30, 60];
